#!/usr/bin/python3.6

from asterisk.ami import AMIClient
from asterisk.ami import SimpleAction

client = AMIClient(address='192.168.100.55',port=5038)
client.login(username='ksdjJJas',secret='123sjj')

action = SimpleAction(
    'Originate',
    Channel='SIP/zadarm',
    Exten=89035911634,
    Priority=1,
    Context='default',
    CallerID='+79530011287',
)
client.send_action(action)
client.logoff()